OceanStore/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OceanStore.BusinessLayer.Managers;
using OceanStore.DataAccesLayer.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OceanStore.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class EmployeeController : Controller
    {
        #region ctor
        private readonly EmployeeManager _employeeManager;
        private readonly PositionManager _positionManager;
        public EmployeeController(EmployeeManager employeeManager, PositionManager positionManager)
        {
            _employeeManager = employeeManager;
            _positionManager = positionManager;
        }
        #endregion

        #region Index
        public async Task<IActionResult> Index()
        {
            List<Employee> employees = await _employeeManager.GetAllEmployee();
            ViewBag.PositionsCount = (await _positionManager.GetAllActivePositions()).Count;
            return View(employees);
        }
        #endregion

        #region Create
        public async Task<IActionResult> Create()
        {
            List<Position> positions = await _positionManager.GetAllActivePositions();
            if (positions.Count == 0)
                return BadRequest();
            ViewBag.Positions = positions;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Employee employee, int? positionId)
        {
            List<Position> positions = await _positionManager.GetAllActivePositions();
            if (positions.Count == 0)
                return BadRequest();
            ViewBag.Positions = positions;
            if (!ModelState.IsValid)
                return View();
            if (positionId == null)
            {
                ModelState.AddModelError("Position.Id", "Select position");
                return View();
            }
            bool IsExistEmail = await _employeeManager.IsExistEmployeeEmail(employee);
            if (IsExistEmail)
            {
                ModelState.AddModelError("Email", "This Email is already exist");
                return View();
            }
            bool IsExistPhoneNumber = await _employeeManager.IsExistEmployeeEmail(employee);
            if (IsExistPhoneNumber)
            {
                ModelState.AddModelError("PhoneNumber", "This PhoneNumber is already exist");
                return View();
            }
            employee.PositionId = (int)positionId;
            await _employeeManager.CreateEmployee(employee);
            return RedirectToAction("Index");
        }
        #endregion

        #region Update
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();
            Employee employee = await _employeeManager.GetEmployeeById((int)id);
            if (employee == null)
                return BadRequest();
            List<Position> positions = await _positionManager.GetAllActivePositions();
            if (positions.Count == 0)
                return BadRequest();
            ViewBag.Positions = positions;
            return View(employee);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Employee employee, int? positionId)
        {
            if (!ModelState.IsValid)
                return View(employee);
            if (id == null)
                return NotFound();
            if (positionId == null)
            {
                ModelState.AddModelError("Position.Id", "Select position");
                return View();
            }
            Employee dbEmployee = await _employeeManager.GetEmployeeById((int)id);
            if (dbEmployee == null)
                return BadRequest();
            List<Position> positions = await _positionManager.GetAllActivePositions();
            if (positions.Count == 0)
                return BadRequest();
            ViewBag.Positions = positions;
            bool isExistEmployeeEmail = await _employeeManager.IsExistEmployeeEmailVariosId(employee);
            if (isExistEmployeeEmail)
            {
                ModelState.AddModelError("", "This Email is already exist");
                return View(employee);
            }
            bool isExistEmployeePhoneNumber = await _employeeManager.IsExistEmployeePhoneNumberVariosId(employee);
            if (isExistEmployeePhoneNumber)
            {
                ModelState.AddModelError("", "This PhoneNumber is already exist");
                return View(employee);
            }
            dbEmployee.PositionId = (int)positionId;
            dbEmployee.Name = employee.Name;
            dbEmployee.Email = employee.Email;
            dbEmployee.PhoneNumber = employee.PhoneNumber;
            dbEmployee.EmployeeDetail = employee.EmployeeDetail;
            await _employeeManager.UpdateEmploye(dbEmployee);
            return RedirectToAction("Index");
        }
        #endregion

        #region Activity
        public async Task<IActionResult> Activity(int? id)
        {
            if (id == null)
                return NotFound();
            Employee employee = await _employeeManager.GetEmployeeById((int)id);
            if (employee == null)
                return BadRequest();
            await _employeeManager.ActivityEmployee(employee);
            return RedirectToAction("Index");
        }
        #endregion

        #region Detail
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
                return NotFound();
            Employee employee = await _employeeManager.GetEmployeeById((int)id);
            if (employee == null)
                return BadRequest();
            ViewBag.Positions = await _positionManager.GetAllPositions();
            return View(employee);
        }
        #endregion
    }
}

OceanStore/Controllers/MailController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OceanStore.BusinessLayer.Managers;
using OceanStore.DataAccesLayer.Models;
using System.Threading.Tasks;

namespace OceanStore.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class MailController : Controller
    {
        #region ctor
        private readonly MailManager _mailManager;
        private readonly EmployeeManager _employeeManager;
        public MailController(MailManager mailManager, EmployeeManager employeeManager)
        {
            _mailManager = mailManager;
            _employeeManager = employeeManager;
        }
        #endregion

        #region Index
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
                return NotFound();
            Employee employee = await _employeeManager.GetEmployeeById((int)id);
            if (employee == null)
                return BadRequest();
            Mail mail = new Mail();
            mail.MailTo = employee.Email;
            return View(mail);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(int? id, Mail mail)
        {
            if (!ModelState.IsValid)
                return View();
            if (id == null)
                return NotFound();
            Employee employee = await _employeeManager.GetEmployeeById((int)id);
            if (employee == null)
                return BadRequest();
            await _mailManager.SendMail(mail.MessageSubject,mail.MessageBody,mail.MailTo);
            return RedirectToAction("Index", "Employee");
        }
        #endregion

        #region SendAll
        public async Task<IActionResult> SendAll()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SendAll(Mail mail)
        {
            if (!ModelState.IsValid)
                return View();
            await _mailManager.SendAllMail(mail);
            return RedirectToAction("Index", "Employee");
        }
        #endregion
    }
}

OceanStore/Controllers/PositionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OceanStore.BusinessLayer.Managers;
using OceanStore.DataAccesLayer.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OceanStore.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class PositionController : Controller
    {
        #region ctor
        private readonly PositionManager _positionManager;
        public PositionController(PositionManager positionManager)
        {
            _positionManager = positionManager;
        }
        #endregion

        #region Index
        public async Task<IActionResult> Index()
        {
            List<Position> positions = await _positionManager.GetAllPositions();
            return View(positions);
        }
        #endregion
        #region Create
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Position position)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            bool IsExist = await _positionManager.IsExistPositionName(position);
            if (IsExist)
            {
                ModelState.AddModelError("Name", "This Position is already exist");
                return View();
            }
            await _positionManager.CreatePosition(position);
            return RedirectToAction("Index");
        }
        #endregion

        #region Update
        public async Task<IActionResult> Update(int id)
        {
            if (id == null)
                return NotFound();
            Position position = await _positionManager.GetPositionById(id);
            if (position == null)
                return BadRequest();
            return View(position);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Position position,int id)
        {
            #region FromGet
            if (id == null)
                return NotFound();
            Position dbPosition = await _positionManager.GetPositionById(id);
            if (dbPosition == null)
                return BadRequest();
            #endregion
            if (!ModelState.IsValid)
                return View(position);
            bool isExist = await _positionManager.IsExistPositionNameVariousId(position);
            if (isExist)
            {
                ModelState.AddModelError("Name", "This Position is already exist");
                return View(position);
            }
            await _positionManager.UpdatePosition(dbPosition,position);
            return RedirectToAction("Index");
        }
        #endregion

        #region Activity
        public async Task<IActionResult> Activity(int? id)
        {
            if (id == null)
                return NotFound();
            Position position = await _positionManager.GetPositionById((int)id);
            if (position == null)
                return BadRequest();
            await _positionManager.ActivityPosition(position);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

OceanStore/Views/Employee/Create.cshtml
@model Employee
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">İşçi Yarat</h4>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Name">Ad</label>
                        <input asp-for="Name" class="form-control">
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EmployeeDetail.Surname">Soyad</label>
                        <input asp-for="EmployeeDetail.Surname" class="form-control">
                        <span asp-validation-for="EmployeeDetail.Surname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EmployeeDetail.FatherName">Ata Adı</label>
                        <input asp-for="EmployeeDetail.FatherName" class="form-control">
                        <span asp-validation-for="EmployeeDetail.FatherName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EmployeeDetail.DateOfBirth">Doğum Tarixi</label>
                        <input asp-for="EmployeeDetail.DateOfBirth" type="date" class="form-control">
                        <span asp-validation-for="EmployeeDetail.DateOfBirth" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EmployeeDetail.Gender">Cinsi</label>
                        <div class="form-check">
                            <input asp-for="EmployeeDetail.Gender" type="radio" value="Kişi" class="form-check-input">
                            <label class="form-check-label">Kisi</label>
                        </div>
                        <div class="form-check">
                            <input asp-for="EmployeeDetail.Gender" type="radio" value="Qadın" class="form-check-input">
                            <label class="form-check-label">Qadin</label>
                        </div>
                        <span asp-validation-for="EmployeeDetail.Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Vəzifə Seçin</label>
                        <select name="positionId" class="form-control text-white">
                            <option selected disabled hidden></option>
                            @foreach (Position position in ViewBag.Positions)
                            {
                                <option value="@position.Id">@position.Name</option>
                            }
                        </select>
                        <span asp-validation-for="Position.Id" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email">Email</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">@("@")</span>
                            </div>
                            <input asp-for="Email" placeholder="email" class="form-control">
                        </div>
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber">Telefon Nömrəsi</label>
                        <span class="text-danger">* 055-444-2332 və ya 55-444-2332</span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">+944</span>
                            </div>
                            <input asp-for="PhoneNumber" class="form-control">
                        </div>
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a asp-action="Index" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

OceanStore/Views/Employee/Detail.cshtml
@model Employee
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">İşçi Yarat</h4>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Name">Ad</label>
                        <input asp-for="Name" class="form-control" disabled>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EmployeeDetail.Surname">Soyad</label>
                        <input asp-for="EmployeeDetail.Surname" class="form-control" disabled>
                        <span asp-validation-for="EmployeeDetail.Surname" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EmployeeDetail.FatherName">Ata Adı</label>
                        <input asp-for="EmployeeDetail.FatherName" class="form-control" disabled>
                        <span asp-validation-for="EmployeeDetail.FatherName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EmployeeDetail.DateOfBirth">Doğum Tarixi</label>
                        <input asp-for="EmployeeDetail.DateOfBirth" type="date" class="form-control" disabled>
                        <span asp-validation-for="EmployeeDetail.DateOfBirth" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @if (Model.EmployeeDetail.Gender != "Qadın")
                        {
                            <label asp-for="EmployeeDetail.Gender">Cinsi</label>
                            <div class="form-check">
                                <input asp-for="EmployeeDetail.Gender" type="radio" value="Kişi" class="form-check-input" checked>
                                <label class="form-check-label">Kisi</label>
                            </div>
                        }
                        else
                        {
                            <div class="form-check">
                                <input asp-for="EmployeeDetail.Gender" type="radio" value="Qadın" class="form-check-input" checked>
                                <label class="form-check-label">Qadin</label>
                            </div>
                        }
                        <span asp-validation-for="EmployeeDetail.Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Vəzifə Seçin</label>
                        <select name="positionId" class="form-control text-white" disabled>
                            <option selected disabled hidden></option>
                            @foreach (Position position in ViewBag.Positions)
                            {
                                if (Model.PositionId == position.Id)
                                {
                                    <option value="@position.Id" selected>@position.Name</option>
                                }
                                else
                                {
                                    <option value="@position.Id">@position.Name</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="Position.Id" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email">Email</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">@("@")</span>
                            </div>
                            <input asp-for="Email" placeholder="email" class="form-control" disabled>
                        </div>
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber">Telefon Nömrəsi</label>
                        <span class="text-danger">* 055-444-2332 və ya 55-444-2332</span>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">+944</span>
                            </div>
                            <input asp-for="PhoneNumber" class="form-control" disabled>
                        </div>
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    @*<button type="submit" class="btn btn-primary mr-2">Submit</button>*@
                    <a asp-action="Index" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

OceanStore/Views/Employee/Index.cshtml
@model List<Employee>

<!-- partial -->
@*<div class="main-panel">*@
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                @if (ViewBag.PositionsCount != 0)
                {
                    <h4 class="card-title">İşçilər</h4>
                    <div style="text-align:end">
                        @if (Model.Count > 1)
                        {
                            <a asp-controller="Mail" asp-action="SendAll" title="Butun işçilərə mail göndər" class="btn badge-success text-white btn-rounded" style="width:80px;height:30px;display:inline-flex;justify-content:center;align-items:center;margin-right:5px">
                                <div class="preview-thumbnail">
                                    <div class="preview-icon badge-success">
                                        <i class="mdi mdi-plus"></i>
                                        <i class="mdi mdi-email"></i>
                                    </div>
                                </div>
                            </a>
                        }
                        <a asp-action="Create" class="btn btn-primary text-white btn-rounded" style="width:80px;height:30px;display:inline-flex;justify-content:center;align-items:center;margin-right:100px" title="Create">
                            <i class="mdi mdi-plus"></i>
                        </a>
                    </div>
                    <div class="table-responsive">
                        <table class="table" id="positionTable">
                            <thead>
                                <tr>
                                    <th class="text-center">Ad</th>
                                    <th class="text-center">Vəzifə</th>
                                    <th class="text-center">Email</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Əməliyyatlar</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (Employee employee in Model)
                                {
                                    <tr>
                                        <td class="text-center">@employee.Name</td>
                                        <td class="text-center">@employee.Position.Name</td>
                                        <td class="text-center">@employee.Email</td>
                                        <td class="text-center">
                                            <span class="@(employee.IsDeactive? "text-danger" : "text-success")">@(employee.IsDeactive ? "Deactive" : "Active")</span>
                                        </td>
                                        <td class="text-center">
                                            <a asp-controller="Mail" asp-action="Index" asp-route-id="@employee.Id" title="Email Gonder" class="badge badge-danger">
                                                <div class="preview-thumbnail">
                                                    <div class="preview-icon bg-danger">
                                                        <i class="mdi mdi-email-open"></i>
                                                    </div>
                                                </div>
                                            </a>
                                            <a asp-action="Detail" asp-route-id="@employee.Id" class="badge badge-info">Detail</a>
                                            <a asp-action="Update" asp-route-id="@employee.Id" class="badge badge-warning">Update</a>
                                            <a asp-action="Activity" asp-route-id="@employee.Id" class="badge @(employee.IsDeactive ? "badge-success" : "badge-danger")">@(employee.IsDeactive ? "Activade" : "Deactivade")</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <h4 class="card-title text-danger">Vəzifə Yarat!</h4>
                    <div class="card">
                        <a asp-controller="Position" asp-action="Create" class="btn btn-primary btn-fw">Vəzifə Yarat</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@*</div>*@
<!-- content-wrapper ends -->
@section Scripts{
    <script>
        $(document).ready(function () {
            $('#positionTable thead tr').clone(true).addClass('filters').appendTo('#positionTable thead');
            $('#positionTable').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
                rowReorder: {
                    dataSrc: 'question_order',
                    selector: 'tr'
                },
                responsive: true,
                columnDefs: [
                    { orderable: true, className: 'reorder', targets: '_all' },
                    { orderable: false, targets: '_all' }
                ],
                scrollY: '200px',
                colReorder: true,


                orderCellsTop: true,
                fixedHeader: true,
                initComplete: function () {
                    var api = this.api();
                    // For each column
                    api.columns().eq(0).each(function (colIdx) {
                        // Set the header cell to contain the input element
                        var cell = $('.filters th').eq($(api.column(colIdx).header()).index());
                        var title = $(cell).text();
                        $(cell).html('<input type="text" placeholder="' + title + '" />');
                        // On every keypress in this input
                        $('input', $('.filters th').eq($(api.column(colIdx).header()).index()))
                            .off('keyup change')
                            .on('keyup change', function (e) {
                                e.stopPropagation();
                                // Get the search value
                                $(this).attr('title', $(this).val());
                                var regexr = '({search})'; //$(this).parents('th').find('select').val();
                                var cursorPosition = this.selectionStart;
                                // Search the column for that value
                                api
                                    .column(colIdx)
                                    .search((this.value != "") ? regexr.replace('{search}', '(((' + this.value + ')))') : "", this.value != "", this.value == "")
                                    .draw();
                                $(this).focus()[0].setSelectionRange(cursorPosition, cursorPosition);
                            });
                    });
                }
            });
        });

    </script>
}